In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler

**Importing the dataset**

In [ ]:
df=pd.read_csv('/content/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
del df['User ID']

In [ ]:
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

**Splitting the dataset into the Training set and Test set**

In [ ]:
x=df.iloc[:,:3].values
y=df.iloc[:,3].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

array([[     1,     60,  42000],
       [     1,     47,  25000],
       [     1,     29,  43000],
       [     1,     26,  32000],
       [     0,     50,  88000],
       [     0,     26,  52000],
       [     1,     35, 108000],
       [     1,     37,  75000],
       [     0,     28,  37000],
       [     1,     46,  79000],
       [     0,     35,  50000],
       [     0,     36,  54000],
       [     0,     37,  57000],
       [     1,     42,  80000],
       [     0,     42,  90000],
       [     0,     40, 142000],
       [     0,     57,  33000],
       [     1,     35,  58000],
       [     1,     28,  59000],
       [     1,     29,  75000],
       [     1,     26,  15000],
       [     0,     29,  28000],
       [     0,     45,  45000],
       [     1,     19,  70000],
       [     0,     30,  79000],
       [     0,     55, 125000],
       [     1,     30, 135000],
       [     1,     19,  76000],
       [     1,     40,  57000],
       [     0,     39,  59000],
       [  

**Feature Scaling**

In [ ]:
sc=StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)

**Fitting K-NN to the Training set**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt

knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=1)

**Predicting the Test set results**

In [ ]:
y_pred=knn.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0])

In [ ]:
df2=pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df2

Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        1          1
..     ...        ...
75       1          1
76       1          1
77       0          1
78       0          0
79       0          0

[80 rows x 2 columns]

**Making the Confusion Matrix**

In [ ]:
from sklearn.metrics import accuracy_score,f1_score,roc_auc_score,confusion_matrix
acc=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
auroc=roc_auc_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print(acc,f1,auroc)
print(conf)

0.8125 0.761904761904762 0.81
[[41  9]
 [ 6 24]]


In [ ]:
from sklearn.model_selection import cross_val_score
import numpy as np

for k in [1,2,3,4,5,6,7,8,9]:
    clf = KNeighborsClassifier(n_neighbors=k) 
    clf.fit(x, y)
    print("K : ", k, " Train Accuracy : ", clf.score(x,y), " Val Accuracy : ", np.mean(cross_val_score(clf, x, y, cv=5))) 

K :  1  Train Accuracy :  0.9975  Val Accuracy :  0.7849999999999999
K :  2  Train Accuracy :  0.9  Val Accuracy :  0.7575000000000001
K :  3  Train Accuracy :  0.8975  Val Accuracy :  0.76
K :  4  Train Accuracy :  0.8625  Val Accuracy :  0.7699999999999999
K :  5  Train Accuracy :  0.8725  Val Accuracy :  0.7674999999999998
K :  6  Train Accuracy :  0.8625  Val Accuracy :  0.7625
K :  7  Train Accuracy :  0.87  Val Accuracy :  0.7675000000000001
K :  8  Train Accuracy :  0.85  Val Accuracy :  0.775
K :  9  Train Accuracy :  0.8675  Val Accuracy :  0.7649999999999999
